# Site settings
title: "My Academic Site"
description: "A website showcasing my research, publications, and academic work."
author: "Your Name"

# Theme settings (using a remote theme example)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal  # optional if using remote_theme
